name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15"
      - name: Install
        run: npm ci
      - name: Unit Tests
        run: npm run test
        env:
          CI: true
      - name: Collect Coverage
        run: npm run coverage && npm run codecov
        env:
          CI: true